default:
  image: registry.gitlab.com/smspp/smspp

stages:
  - build
  - test
  - pages

build_job:
  stage: build
  script:
    - cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    - cmake --build build
  artifacts:
    when: on_success
    paths:
      - build
  only:
    changes:
      - include/*
      - src/*
      - test/*
      - CMakeLists.txt

test_job:
  stage: test
  script:
    - cmake --build build --target test
  only:
    changes:
      - include/*
      - src/*
      - test/*
      - CMakeLists.txt

pages_job:
  image: alpine
  stage: pages
  before_script:
    - apk update
    - apk add doxygen
  ### Uncomment the following line if you use graphviz dot graphs
  ##- apk add ttf-freefont graphviz
  script:
    - doxygen doxygen/Doxyfile
    - mv doc/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master
