default:
  image: registry.gitlab.com/smspp/smspp

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    - cmake --build build
  artifacts:
    paths:
      - build
  only:
    changes:
      - include/*
      - src/*
      - test/*
      - CMakeLists.txt

test:
  stage: test
  dependencies:
    - build
  script:
    - cmake --build build --target test

deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - cd build && cpack -G "TGZ;ZIP;TBZ2"
  artifacts:
    paths:
      - build/*.tar.gz
      - build/*.tar.bz2
      - build/*.zip
  only:
    - tags

pages:
  image: alpine
  stage: deploy
  before_script:
    - apk update
    - apk add doxygen
  ### Uncomment the following line if you use graphviz dot graphs
  ##- apk add ttf-freefont graphviz
  script:
    - doxygen doxygen/Doxyfile
    - mv doc/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master
